# Generated by Django 3.0.7 on 2020-06-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=300)),
                ('price', models.FloatField(default=5)),
                ('espresso', models.CharField(choices=[('signature', 'Espresso Signature Blend'), ('blonde', 'Espresso Blonde'), ('darkroasted', 'Espresso Darkroasted'), ('none', 'None')], default='Espresso Signature Blend', max_length=20)),
                ('milk', models.CharField(choices=[('2% Milk', '2%'), ('non-fat', 'Non-fat'), ('soy', 'Soy')], default='2%', max_length=20)),
                ('shot', models.CharField(choices=[('double', 'Double'), ('triple', 'Triple'), ('quadruple', 'Quadruple'), ('none', 'None')], default='double', max_length=20)),
                ('customize', models.CharField(default='none', max_length=100)),
                ('img_url', models.TextField()),
                ('preview_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swirl.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swirl.Item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swirl.Order')),
            ],
        ),
    ]
