# Generated by Django 3.0.7 on 2020-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swirl', '0003_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
